site_name: Monitoring and Observability 
nav:
  - Prometheus: index.md
  - Prometheus Install: prometheus-install.md
  - Grafana: grafana.md
theme:
  name: material
  nav_style: dark
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
